--- @meta

CF = {}
DailyProvisioning = {}
LibAddonMenu2 = {}
LibChatMessage = {}
LibDebugLogger = {}
LibSavedVars = {}
RuEsoVariables = {}

ZO_SHARED_INFORMATION_AREA_SUPPRESSION_CATEGORIES = {}

--- @param recipeListIndex luaindex
--- @param recipeIndex luaindex
--- @param numIterations? integer
function CraftProvisionerItem(recipeListIndex, recipeIndex, numIterations) end

--- @param namespace string
--- @param func function
function CALLBACK_MANAGER:UnregisterCallback(namespace, func) end

--- @class PLAYER_INVENTORY
--- @field inventories table
--- @field isListDirty boolean

--- @class menuBar:Control
--- @field m_object any

--- @class modeBar:Control
--- @field menuBar menuBar
modeBar = {}
--- @param fragment integer
function modeBar:SelectFragment(fragment) end

--- @class FENCE_KEYBOARD
--- @field modeBar modeBar

--- @class PROVISIONER
--- @field recipeTree ZO_Tree

--- @class SHARED_INVENTORY
--- @field bagCache table

FOB_ALERT_COLOUR = 0
FOB_ALERT_FONT = 0
FOB_ALERT_ICON = 0
FOB_ALERT_SHADOW = 0
FOB_CHEESE_ALERT = 0
FOB_CHEESE_WARNING = 0
FOB_COFFEE_ALERT = 0
FOB_COFFEE_WARNING = 0
FOB_COMPANION_MENU = 0
FOB_DISABLE_COMPANION_INTERACTION = 0
FOB_DISABLED = 0
FOB_DISMISS_COMPANION = 0
FOB_ENABLED = 0
FOB_SHOWSUMMONING = 0
FOB_SUMMONING = 0
FOB_SUMMONINGCOLOUR = 0
FOB_TOGGLE = 0
FOB_TOGGLE_COMPANION = 0
FOB_WARNING = 0
FOB_CATCH = 0
FOB_COLLECT = 0
FOB_EXAMINE = 0
FOB_LOOT = 0
FOB_OPEN = 0
FOB_SEARCH = 0
FOB_TALK = 0
FOB_TAKE = 0
FOB_USE = 0
FOB_BOOKSHELF = 0
FOB_DARK_BROTHERHOOD = 0
FOB_MAGES_GUILD = 0
FOB_MEDICAL = 0
FOB_NIRNROOT = 0
FOB_OUTFIT_STATION = 0
FOB_OUTLAWS_REFUGE = 0
FOB_PSIJIC_PORTAL = 0
FOB_RITUAL = 0
FOB_THIEVES_DEN = 0
FOB_CADWELL = 0
FOB_IGNORE_INSECTS = 0
FOB_IGNORE_MIRRI_INSECTS = 0
FOB_IGNORE_ALL_INSECTS = 0
FOB_PREVENT_BLADE_OF_WOE = 0
FOB_PREVENT_BOOKSHELVES = 0
FOB_PREVENT_CADWELL = 0
FOB_PREVENT_CRIMINAL = 0
FOB_PREVENT_DARK_BROTHERHOOD = 0
FOB_PREVENT_EDICTS = 0
FOB_PREVENT_FENCE = 0
FOB_PREVENT_FISHING = 0
FOB_PREVENT_LOREBOOKS = 0
FOB_PREVENT_MAGES_GUILD = 0
FOB_PREVENT_MUSHROOM = 0
FOB_PREVENT_NIRNROOT = 0
FOB_PREVENT_OUTFIT = 0
FOB_PREVENT_OUTLAW = 0
FOB_PREVENT_PICKPOCKETING = 0
FOB_PREVENT_PSIJIC = 0
FOB_PREVENT_SPECIFIC_TT = 0
FOB_PREVENT_TREASURES = 0
FOB_BLACKREACH_JELLY = 0
FOB_BRIGHT_MOONS_LUNAR_MOTH = 0
FOB_BUTTERFLY = 0
FOB_CAVE_JELLY = 0
FOB_DRAGONFLY = 0
FOB_FETCHERFLY = 0
FOB_FLESHFLIES = 0
FOB_ISLAND_MOTH = 0
FOB_MOON_KISSED_JELLY = 0
FOB_NETCH_CALF = 0
FOB_SEHTS_DOVAH_FLY = 0
FOB_SWAMP_JELLY = 0
FOB_TORCHBUG = 0
FOB_WAFT = 0
FOB_WASP = 0
FOB_WINTER_MOTH = 0
FOB_BLANCHED_RUSSULA_CAP = 0
FOB_BLIGHT_BOG_MUSHROOM = 0
FOB_BLUE_ENTOLOMA = 0
FOB_CALDERA_MUSHROOM = 0
FOB_CANIS_CAP_MUSHROOM = 0
FOB_DUSK_MUSHROOM = 0
FOB_EMETIC_RUSSULA = 0
FOB_GLEAMCAP = 0
FOB_GLOOM_MOREL = 0
FOB_GLOOMSPORE_AGARIC = 0
FOB_GRAVEN_CAP = 0
FOB_IMP_STOOL = 0
FOB_IRONSTALK_MUSHROOM = 0
FOB_KWAMA_CAP = 0
FOB_LAVANDER_CAP = 0
FOB_LUMINOUS_RUSSULA = 0
FOB_NAMIRAS_ROT = 0
FOB_PARASOL_LICHEN = 0
FOB_PRUNE_MOREL_MUSHROOM = 0
FOB_STINKHORN = 0
FOB_VIOLET_COPRINUS = 0
FOB_WHITE_CAP = 0
FOB_DAMAGED = 0
FOB_WARN_BROKEN = 0
FOB_RETICLE = 0
FOB_SEBASTIAN_BRUTYA = 0
FOB_MAZZA_MIRRI = 0
FOB_LADY_LLARELS_SHELTER = 0
FOB_BLACKHEART_HAVEN = 0
FOB_SHINYTRADE = 0
FOB_EVELI_SHARP_ARROW = 0
FOB_LERISA_DIE_GERISSENE = 0

DP_BULK_HEADER = 0
