--ZO_CreateStringId("SI_BINDING_NAME_FOB_COMPANION_MENU", GetString(_G.FOB_COMPANION_MENU))
ZO_CreateStringId("SI_BINDING_NAME_FOB_TOGGLE", GetString(_G.FOB_TOGGLE))
--ZO_CreateStringId("SI_BINDING_NAME_FOB_DISMISS_COMPANION", GetString(_G.FOB_DISMISS_COMPANION))
ZO_CreateStringId("SI_BINDING_NAME_FOB_TOGGLE_COMPANION", GetString(_G.FOB_TOGGLE_COMPANION))